# mise configuration for Video Downloader
# Tool version management and task runner

[tools]
# Runtime and language versions only
node = "20.10.0"
bun = "latest"

[env]
# Environment variables
NODE_ENV = "development"
ELECTRON_IS_DEV = "1"
DEV_PORT = "3000"

# Database
DB_PATH = "./data/video-downloader.db"
DB_LOG_LEVEL = "info"

# Logging
LOG_LEVEL = "debug"

# Security
ENABLE_CSP = "true"
ALLOW_EXTERNAL_URLS = "false"

# Download settings
MAX_CONCURRENT_DOWNLOADS = "3"
SEGMENT_RETRY_COUNT = "3"

[tasks.install]
description = "Install dependencies"
run = "bun install"

[tasks.dev]
description = "Start development server"
run = "bun run dev"
depends = ["install"]

[tasks.build]
description = "Build for production"
run = "bun run build"
depends = ["clean", "typecheck"]

[tasks.test]
description = "Run all tests"
run = "bun run test"

[tasks."test:watch"]
description = "Run tests in watch mode"
run = "bun run test:watch"

[tasks."test:coverage"]
description = "Run tests with coverage"
run = "bun run test:coverage"

[tasks."test:unit"]
description = "Run unit tests only"
run = "bun run test:unit"

[tasks."test:e2e"]
description = "Run E2E tests"
run = "bun run test:e2e"
depends = ["build"]

[tasks.lint]
description = "Run ESLint"
run = "bun run lint"

[tasks."lint:fix"]
description = "Run ESLint with auto-fix"
run = "bun run lint:fix"

[tasks.format]
description = "Format code with Prettier"
run = "bun run format"

[tasks."format:check"]
description = "Check code formatting"
run = "bun run format:check"

[tasks.typecheck]
description = "Run TypeScript type checking"
run = "bun run typecheck"

[tasks.check]
description = "Run all checks (type, lint, format)"
depends = ["typecheck", "lint", "format:check"]

[tasks."db:generate"]
description = "Generate database migrations"
run = "bun run db:generate"

[tasks."db:push"]
description = "Push database changes"
run = "bun run db:push"

[tasks."db:studio"]
description = "Open Drizzle Studio"
run = "bun run db:studio"

[tasks."db:migrate"]
description = "Run database migrations"
run = "bun run db:migrate"
depends = ["db:generate"]

[tasks.clean]
description = "Clean build artifacts (OS command)"
run = "rm -rf dist dist-electron"

[tasks."clean:all"]
description = "Clean everything including dependencies (OS command)"
run = "rm -rf dist dist-electron node_modules .bun bun.lockb"

[tasks."clean:cache"]
description = "Clean Bun cache (OS command)"
run = "rm -rf .bun ~/.bun/cache"

[tasks.dist]
description = "Package application for distribution"
run = "bunx electron-builder"
depends = ["build"]

[tasks."dist:mac"]
description = "Package for macOS"
run = "bunx electron-builder --mac"
depends = ["build"]

[tasks."dist:win"]
description = "Package for Windows"
run = "bunx electron-builder --win"
depends = ["build"]

[tasks."dist:linux"]
description = "Package for Linux"
run = "bunx electron-builder --linux"
depends = ["build"]

[tasks.electron]
description = "Run Electron (production mode)"
run = "bun run electron"
depends = ["build"]

[tasks."electron:dev"]
description = "Run Electron (development mode)"
run = "bun run electron:dev"
env = { NODE_ENV = "development", ELECTRON_IS_DEV = "1" }

[tasks.update]
description = "Update dependencies"
run = """
bunx npm-check-updates -u
bun install
"""

[tasks.audit]
description = "Run security audit"
run = "bun audit"

[tasks.prepare]
description = "Prepare Git hooks with Husky"
run = "bunx husky"

[tasks.docs]
description = "Generate API documentation"
run = "bunx typedoc --out docs/api src"

[tasks.info]
description = "Show project information"
run = """
echo "Video Downloader - Electron App"
echo "================================"
echo "Node: $(node --version)"
echo "Bun: $(bun --version)"
echo ""
echo "Run 'mise tasks' to see all available tasks"
"""

# Task aliases for convenience
[tasks.t]
alias = "test"

[tasks.d]
alias = "dev"

[tasks.b]
alias = "build"

[tasks.c]
alias = "check"

# Composite tasks
[tasks.ci]
description = "Run CI checks"
depends = ["check", "test", "build"]

[tasks.release]
description = "Prepare a release"
depends = ["check", "test", "build", "dist"]

[tasks.setup]
description = "Setup development environment"
run = "bun run scripts/setup.ts"

# Watch tasks
[tasks.watch]
description = "Watch mode for development"
run = """
bunx concurrently -n "main,preload,renderer" \
  "bun build src/main/index.ts --outdir dist/main --watch" \
  "bun build src/preload/index.ts --outdir dist/preload --watch" \
  "bunx vite"
"""

[tasks."watch:main"]
description = "Watch main process only"
run = "bun build src/main/index.ts --outdir dist/main --watch"

[tasks."watch:preload"]
description = "Watch preload script only"
run = "bun build src/preload/index.ts --outdir dist/preload --watch"

[tasks."watch:renderer"]
description = "Watch renderer process only"
run = "bunx vite"