# Bun configuration for Video Downloader

# Test runner configuration
[test]
# Test file patterns - use specific extensions
preload = ["./src/test/setup.ts"]
# Root directory for test discovery
root = "./src"
# Only run .bun.test.ts files with bun test
pattern = "**/*.bun.test.{ts,tsx}"

# Coverage settings
coverage = false
coverageThreshold = 60

# Timeout for tests (ms)
timeout = 5000

# Install settings
[install]
# Save exact versions
exact = true

# Dev settings
[dev]
port = 3000