name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_ENV: test

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          cache: true
          
      - name: Install tools
        run: mise install
        
      - name: Install dependencies
        run: mise run install
        
      - name: Run type check
        run: mise run typecheck
        
      - name: Run linter
        run: mise run lint
        
      - name: Check formatting
        run: mise run format:check
        
      - name: Run unit tests
        run: mise run test:unit
        
      - name: Run tests with coverage
        run: mise run test:coverage
        
      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
        
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          cache: true
          
      - name: Install tools
        run: mise install
        
      - name: Install dependencies
        run: mise run install
        
      - name: Build application
        run: mise run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/
          
  e2e:
    name: E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          cache: true
          
      - name: Install tools
        run: mise install
        
      - name: Install dependencies
        run: mise run install
        
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/
          
      - name: Install Playwright browsers
        run: bunx playwright install --with-deps
        
      - name: Run E2E tests
        run: mise run test:e2e
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 30
          
  release:
    name: Release Check
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          cache: true
          
      - name: Install tools
        run: mise install
        
      - name: Install dependencies
        run: mise run install
        
      - name: Run release checks
        run: |
          echo "Running release checks..."
          mise run check
          mise run test
          mise run build
          echo "✅ All release checks passed"